[book]
authors = ["katopz <katopz@gmail.com>"]
language = "en"
multilingual = false
src = "src"
title = "Gist of Rust ðŸ¦€"

## Uncomment this section to regennerate theme
# [preprocessor.theme]
# pagetoc = true
# sidebar-width = "250px"

[output.html]
# theme = "theme"
default-theme = "coal"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/gist-rs/book"
additional-css = ["theme/css/variables.css", "theme/css/general.css", "theme/css/chrome.css", "theme/highlight.css"]
# additional-js = ["theme/pagetoc.js"]
additional-js = ["js/helper.js"]

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true

[output.html.print]
enable = false

# Uncomment this section to regenerate theme
[output.theme-ace]
theme-white = "xcode"
theme-dark = "monokai"
